/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.0.11.0 (NJsonSchema v9.13.13.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class AccountsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    /**
     * @param pageSize (optional) 
     * @param orderBy (optional) 
     * @param orderDirection (optional) 
     * @param continuationToken (optional) 
     * @return Success
     */
    list(pageSize: number | null | undefined, orderBy: OrderBy | null | undefined, orderDirection: OrderDirection | null | undefined, continuationToken: string | null | undefined): Promise<AccountListResultsViewModel> {
        let url_ = this.baseUrl + "/api/accounts/list?";
        if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&"; 
        if (orderBy !== undefined)
            url_ += "orderBy=" + encodeURIComponent("" + orderBy) + "&"; 
        if (orderDirection !== undefined)
            url_ += "orderDirection=" + encodeURIComponent("" + orderDirection) + "&"; 
        if (continuationToken !== undefined)
            url_ += "continuationToken=" + encodeURIComponent("" + continuationToken) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processList(_response);
        });
    }

    protected processList(response: Response): Promise<AccountListResultsViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? AccountListResultsViewModel.fromJS(resultData200) : new AccountListResultsViewModel();
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccountListResultsViewModel>(<any>null);
    }

    /**
     * @param query (optional) 
     * @param page (optional) 
     * @param pageSize (optional) 
     * @param orderBy (optional) 
     * @param orderDirection (optional) 
     * @return Success
     */
    search(query: string | null | undefined, page: number | null | undefined, pageSize: number | null | undefined, orderBy: OrderBy2 | null | undefined, orderDirection: OrderDirection2 | null | undefined): Promise<AccountListResultsViewModel> {
        let url_ = this.baseUrl + "/api/accounts/search?";
        if (query !== undefined)
            url_ += "query=" + encodeURIComponent("" + query) + "&"; 
        if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&"; 
        if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&"; 
        if (orderBy !== undefined)
            url_ += "orderBy=" + encodeURIComponent("" + orderBy) + "&"; 
        if (orderDirection !== undefined)
            url_ += "orderDirection=" + encodeURIComponent("" + orderDirection) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSearch(_response);
        });
    }

    protected processSearch(response: Response): Promise<AccountListResultsViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? AccountListResultsViewModel.fromJS(resultData200) : new AccountListResultsViewModel();
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccountListResultsViewModel>(<any>null);
    }

    /**
     * @return Success
     */
    details(nameKey: string): Promise<AccountDetailsViewModel> {
        let url_ = this.baseUrl + "/api/accounts/details/{nameKey}";
        if (nameKey === undefined || nameKey === null)
            throw new Error("The parameter 'nameKey' must be defined.");
        url_ = url_.replace("{nameKey}", encodeURIComponent("" + nameKey)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDetails(_response);
        });
    }

    protected processDetails(response: Response): Promise<AccountDetailsViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? AccountDetailsViewModel.fromJS(resultData200) : new AccountDetailsViewModel();
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccountDetailsViewModel>(<any>null);
    }

    /**
     * @param createAccountServiceModel (optional) 
     * @return Success
     */
    create(createAccountServiceModel: CreateAccountServiceModel | null | undefined): Promise<CreateAccountCommandResponse> {
        let url_ = this.baseUrl + "/api/accounts/create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createAccountServiceModel);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json", 
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<CreateAccountCommandResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? CreateAccountCommandResponse.fromJS(resultData200) : new CreateAccountCommandResponse();
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateAccountCommandResponse>(<any>null);
    }

    /**
     * @param id (optional) 
     * @param value (optional) 
     * @return Success
     */
    update(id: number | null | undefined, value: string | null | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/accounts/update?";
        if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(value);

        let options_ = <RequestInit>{
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json", 
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }

    /**
     * @param id (optional) 
     * @return Success
     */
    delete(id: string | null | undefined): Promise<BaseResponse> {
        let url_ = this.baseUrl + "/api/accounts/delete?";
        if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "DELETE",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<BaseResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? BaseResponse.fromJS(resultData200) : new BaseResponse();
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BaseResponse>(<any>null);
    }
}

export class AccountListResultsViewModel implements IAccountListResultsViewModel {
    count?: number | undefined;
    hasMoreResults?: boolean | undefined;
    accounts?: AccountListViewItem[] | undefined;
    editEnabled?: boolean | undefined;
    deleteEnabled?: boolean | undefined;
    continuationToken?: string | undefined;

    constructor(data?: IAccountListResultsViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.count = data["count"];
            this.hasMoreResults = data["hasMoreResults"];
            if (data["accounts"] && data["accounts"].constructor === Array) {
                this.accounts = [];
                for (let item of data["accounts"])
                    this.accounts.push(AccountListViewItem.fromJS(item));
            }
            this.editEnabled = data["editEnabled"];
            this.deleteEnabled = data["deleteEnabled"];
            this.continuationToken = data["continuationToken"];
        }
    }

    static fromJS(data: any): AccountListResultsViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new AccountListResultsViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["count"] = this.count;
        data["hasMoreResults"] = this.hasMoreResults;
        if (this.accounts && this.accounts.constructor === Array) {
            data["accounts"] = [];
            for (let item of this.accounts)
                data["accounts"].push(item.toJSON());
        }
        data["editEnabled"] = this.editEnabled;
        data["deleteEnabled"] = this.deleteEnabled;
        data["continuationToken"] = this.continuationToken;
        return data; 
    }
}

export interface IAccountListResultsViewModel {
    count?: number | undefined;
    hasMoreResults?: boolean | undefined;
    accounts?: AccountListViewItem[] | undefined;
    editEnabled?: boolean | undefined;
    deleteEnabled?: boolean | undefined;
    continuationToken?: string | undefined;
}

export class AccountListViewItem implements IAccountListViewItem {
    id?: string | undefined;
    name?: string | undefined;
    nameKey?: string | undefined;
    createdDate?: Date | undefined;

    constructor(data?: IAccountListViewItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.name = data["name"];
            this.nameKey = data["nameKey"];
            this.createdDate = data["createdDate"] ? new Date(data["createdDate"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): AccountListViewItem {
        data = typeof data === 'object' ? data : {};
        let result = new AccountListViewItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["nameKey"] = this.nameKey;
        data["createdDate"] = this.createdDate ? this.createdDate.toISOString() : <any>undefined;
        return data; 
    }
}

export interface IAccountListViewItem {
    id?: string | undefined;
    name?: string | undefined;
    nameKey?: string | undefined;
    createdDate?: Date | undefined;
}

export class AccountDetailsViewModel implements IAccountDetailsViewModel {
    account?: Account | undefined;
    editEnabled?: boolean | undefined;
    deleteEnabled?: boolean | undefined;

    constructor(data?: IAccountDetailsViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.account = data["account"] ? Account.fromJS(data["account"]) : <any>undefined;
            this.editEnabled = data["editEnabled"];
            this.deleteEnabled = data["deleteEnabled"];
        }
    }

    static fromJS(data: any): AccountDetailsViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new AccountDetailsViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["account"] = this.account ? this.account.toJSON() : <any>undefined;
        data["editEnabled"] = this.editEnabled;
        data["deleteEnabled"] = this.deleteEnabled;
        return data; 
    }
}

export interface IAccountDetailsViewModel {
    account?: Account | undefined;
    editEnabled?: boolean | undefined;
    deleteEnabled?: boolean | undefined;
}

export class Account implements IAccount {
    id?: string | undefined;
    name?: string | undefined;
    nameKey?: string | undefined;
    users?: User[] | undefined;

    constructor(data?: IAccount) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.name = data["name"];
            this.nameKey = data["nameKey"];
            if (data["users"] && data["users"].constructor === Array) {
                this.users = [];
                for (let item of data["users"])
                    this.users.push(User.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Account {
        data = typeof data === 'object' ? data : {};
        let result = new Account();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["nameKey"] = this.nameKey;
        if (this.users && this.users.constructor === Array) {
            data["users"] = [];
            for (let item of this.users)
                data["users"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IAccount {
    id?: string | undefined;
    name?: string | undefined;
    nameKey?: string | undefined;
    users?: User[] | undefined;
}

export class User implements IUser {
    id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;

    constructor(data?: IUser) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.name = data["name"];
            this.email = data["email"];
        }
    }

    static fromJS(data: any): User {
        data = typeof data === 'object' ? data : {};
        let result = new User();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["email"] = this.email;
        return data; 
    }
}

export interface IUser {
    id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
}

export class CreateAccountServiceModel implements ICreateAccountServiceModel {
    name?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    email?: string | undefined;

    constructor(data?: ICreateAccountServiceModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.name = data["name"];
            this.firstName = data["firstName"];
            this.lastName = data["lastName"];
            this.email = data["email"];
        }
    }

    static fromJS(data: any): CreateAccountServiceModel {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAccountServiceModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["email"] = this.email;
        return data; 
    }
}

export interface ICreateAccountServiceModel {
    name?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    email?: string | undefined;
}

export class CreateAccountCommandResponse implements ICreateAccountCommandResponse {
    validationIssues?: ValidationIssue[] | undefined;
    account?: Account | undefined;
    isSuccess?: boolean | undefined;
    message?: string | undefined;

    constructor(data?: ICreateAccountCommandResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            if (data["validationIssues"] && data["validationIssues"].constructor === Array) {
                this.validationIssues = [];
                for (let item of data["validationIssues"])
                    this.validationIssues.push(ValidationIssue.fromJS(item));
            }
            this.account = data["account"] ? Account.fromJS(data["account"]) : <any>undefined;
            this.isSuccess = data["isSuccess"];
            this.message = data["message"];
        }
    }

    static fromJS(data: any): CreateAccountCommandResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAccountCommandResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.validationIssues && this.validationIssues.constructor === Array) {
            data["validationIssues"] = [];
            for (let item of this.validationIssues)
                data["validationIssues"].push(item.toJSON());
        }
        data["account"] = this.account ? this.account.toJSON() : <any>undefined;
        data["isSuccess"] = this.isSuccess;
        data["message"] = this.message;
        return data; 
    }
}

export interface ICreateAccountCommandResponse {
    validationIssues?: ValidationIssue[] | undefined;
    account?: Account | undefined;
    isSuccess?: boolean | undefined;
    message?: string | undefined;
}

export class ValidationIssue implements IValidationIssue {
    propertyName?: string | undefined;
    propertyFailures?: string[] | undefined;

    constructor(data?: IValidationIssue) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.propertyName = data["propertyName"];
            if (data["propertyFailures"] && data["propertyFailures"].constructor === Array) {
                this.propertyFailures = [];
                for (let item of data["propertyFailures"])
                    this.propertyFailures.push(item);
            }
        }
    }

    static fromJS(data: any): ValidationIssue {
        data = typeof data === 'object' ? data : {};
        let result = new ValidationIssue();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["propertyName"] = this.propertyName;
        if (this.propertyFailures && this.propertyFailures.constructor === Array) {
            data["propertyFailures"] = [];
            for (let item of this.propertyFailures)
                data["propertyFailures"].push(item);
        }
        return data; 
    }
}

export interface IValidationIssue {
    propertyName?: string | undefined;
    propertyFailures?: string[] | undefined;
}

export class BaseResponse implements IBaseResponse {
    validationIssues?: ValidationIssue[] | undefined;
    isSuccess?: boolean | undefined;
    message?: string | undefined;

    constructor(data?: IBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            if (data["validationIssues"] && data["validationIssues"].constructor === Array) {
                this.validationIssues = [];
                for (let item of data["validationIssues"])
                    this.validationIssues.push(ValidationIssue.fromJS(item));
            }
            this.isSuccess = data["isSuccess"];
            this.message = data["message"];
        }
    }

    static fromJS(data: any): BaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.validationIssues && this.validationIssues.constructor === Array) {
            data["validationIssues"] = [];
            for (let item of this.validationIssues)
                data["validationIssues"].push(item.toJSON());
        }
        data["isSuccess"] = this.isSuccess;
        data["message"] = this.message;
        return data; 
    }
}

export interface IBaseResponse {
    validationIssues?: ValidationIssue[] | undefined;
    isSuccess?: boolean | undefined;
    message?: string | undefined;
}

export enum OrderBy {
    Name = "Name", 
    NameKey = "NameKey", 
    CreatedDate = "CreatedDate", 
}

export enum OrderDirection {
    ASC = "ASC", 
    DESC = "DESC", 
}

export enum OrderBy2 {
    Name = "Name", 
    NameKey = "NameKey", 
    CreatedDate = "CreatedDate", 
}

export enum OrderDirection2 {
    ASC = "ASC", 
    DESC = "DESC", 
}

export class SwaggerException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if(result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}